version: '2'
services:

# Our Redis service:
  redis:  
    image: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379"
# Cassandra clusters
  cassandra-1:
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"

# MongoDB Service:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /opt/data-mongodb:/bitnami
