version: '2'
services:

# Our Redis service:
  redis:  
    image: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379"
# Cassandra clusters
  cassandra:
    image: bitnami/cassandra:latest
    volumes:
      - ./cassandra.yaml:/bitnami
    #   - ./data/cassandra-1:/var/lib/cassandra:rw
# MongoDB Service:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /opt/data-mongodb:/bitnami
