version: '2'
services:

# Our Redis service:
  redis:  
    image: redis
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    ports:
      - "6379"
# Cassandra clusters
  cassandra-1:
    image: cassandra:latest
    command: /bin/bash -c "sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh cassandra -f"
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
    ports:
      - "32772:7000"
      - "32771:7001"
      - "32770:7199"
      - "32769:9042"
      - "32768:9160"
# MongoDB Service:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /opt/data-mongodb:/bitnami
